### ISSUE TITLE
Redirect Back To Java Application

### ISSUE THREAD

**Issue by DV8FromTheCode** [HayateLaTech/OAuth2Discord#6]
Is it possible for the Discord OAuth to redirect back to the java application?

**Comment by HayateLaTech** [comment]
There's a `setRedirectURI` function on the OAuth builder if that's what you mean. That's the url that's going to get called after the user got redirected to discord and accepted the OAuth page there.

On that URL you'll want to exchange the Code from the get parameters and get all the information of the user. From there you can do what you want, depending on the framework you're using you should be able to call a redirect after the whole OAuth process yourself.
